/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductThinkingRouteImport } from './routes/product-thinking'
import { Route as CommunityStrategyRouteImport } from './routes/community-strategy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as AuthenticatedHiringAlfredRouteImport } from './routes/_authenticated/hiring-alfred'

const ProductThinkingRoute = ProductThinkingRouteImport.update({
  id: '/product-thinking',
  path: '/product-thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStrategyRoute = CommunityStrategyRouteImport.update({
  id: '/community-strategy',
  path: '/community-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHiringAlfredRoute =
  AuthenticatedHiringAlfredRouteImport.update({
    id: '/hiring-alfred',
    path: '/hiring-alfred',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-strategy': typeof CommunityStrategyRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/hiring-alfred': typeof AuthenticatedHiringAlfredRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-strategy': typeof CommunityStrategyRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/hiring-alfred': typeof AuthenticatedHiringAlfredRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-strategy': typeof CommunityStrategyRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/_authenticated/hiring-alfred': typeof AuthenticatedHiringAlfredRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community-strategy'
    | '/product-thinking'
    | '/hiring-alfred'
    | '/case-studies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-strategy'
    | '/product-thinking'
    | '/hiring-alfred'
    | '/case-studies/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community-strategy'
    | '/product-thinking'
    | '/_authenticated/hiring-alfred'
    | '/case-studies/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityStrategyRoute: typeof CommunityStrategyRoute
  ProductThinkingRoute: typeof ProductThinkingRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/product-thinking': {
      id: '/product-thinking'
      path: '/product-thinking'
      fullPath: '/product-thinking'
      preLoaderRoute: typeof ProductThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-strategy': {
      id: '/community-strategy'
      path: '/community-strategy'
      fullPath: '/community-strategy'
      preLoaderRoute: typeof CommunityStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hiring-alfred': {
      id: '/_authenticated/hiring-alfred'
      path: '/hiring-alfred'
      fullPath: '/hiring-alfred'
      preLoaderRoute: typeof AuthenticatedHiringAlfredRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHiringAlfredRoute: typeof AuthenticatedHiringAlfredRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHiringAlfredRoute: AuthenticatedHiringAlfredRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityStrategyRoute: CommunityStrategyRoute,
  ProductThinkingRoute: ProductThinkingRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
