/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as RecognitionRouteImport } from './routes/recognition'
import { Route as ProductThinkingRouteImport } from './routes/product-thinking'
import { Route as MediaRouteImport } from './routes/media'
import { Route as HiringAlfredRouteImport } from './routes/hiring-alfred'
import { Route as DebugEnvRouteImport } from './routes/debug-env'
import { Route as CommunityStrategyRouteImport } from './routes/community-strategy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesRoomzRouteImport } from './routes/case-studies.roomz'
import { Route as CaseStudiesOsmosisRouteImport } from './routes/case-studies.osmosis'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const RecognitionRoute = RecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductThinkingRoute = ProductThinkingRouteImport.update({
  id: '/product-thinking',
  path: '/product-thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringAlfredRoute = HiringAlfredRouteImport.update({
  id: '/hiring-alfred',
  path: '/hiring-alfred',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEnvRoute = DebugEnvRouteImport.update({
  id: '/debug-env',
  path: '/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStrategyRoute = CommunityStrategyRouteImport.update({
  id: '/community-strategy',
  path: '/community-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoomzRoute = CaseStudiesRoomzRouteImport.update({
  id: '/case-studies/roomz',
  path: '/case-studies/roomz',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesOsmosisRoute = CaseStudiesOsmosisRouteImport.update({
  id: '/case-studies/osmosis',
  path: '/case-studies/osmosis',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-strategy': typeof CommunityStrategyRoute
  '/debug-env': typeof DebugEnvRoute
  '/hiring-alfred': typeof HiringAlfredRoute
  '/media': typeof MediaRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/recognition': typeof RecognitionRoute
  '/story': typeof StoryRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/osmosis': typeof CaseStudiesOsmosisRoute
  '/case-studies/roomz': typeof CaseStudiesRoomzRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-strategy': typeof CommunityStrategyRoute
  '/debug-env': typeof DebugEnvRoute
  '/hiring-alfred': typeof HiringAlfredRoute
  '/media': typeof MediaRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/recognition': typeof RecognitionRoute
  '/story': typeof StoryRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/osmosis': typeof CaseStudiesOsmosisRoute
  '/case-studies/roomz': typeof CaseStudiesRoomzRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-strategy': typeof CommunityStrategyRoute
  '/debug-env': typeof DebugEnvRoute
  '/hiring-alfred': typeof HiringAlfredRoute
  '/media': typeof MediaRoute
  '/product-thinking': typeof ProductThinkingRoute
  '/recognition': typeof RecognitionRoute
  '/story': typeof StoryRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/osmosis': typeof CaseStudiesOsmosisRoute
  '/case-studies/roomz': typeof CaseStudiesRoomzRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-strategy'
    | '/debug-env'
    | '/hiring-alfred'
    | '/media'
    | '/product-thinking'
    | '/recognition'
    | '/story'
    | '/case-studies/$slug'
    | '/case-studies/osmosis'
    | '/case-studies/roomz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-strategy'
    | '/debug-env'
    | '/hiring-alfred'
    | '/media'
    | '/product-thinking'
    | '/recognition'
    | '/story'
    | '/case-studies/$slug'
    | '/case-studies/osmosis'
    | '/case-studies/roomz'
  id:
    | '__root__'
    | '/'
    | '/community-strategy'
    | '/debug-env'
    | '/hiring-alfred'
    | '/media'
    | '/product-thinking'
    | '/recognition'
    | '/story'
    | '/case-studies/$slug'
    | '/case-studies/osmosis'
    | '/case-studies/roomz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityStrategyRoute: typeof CommunityStrategyRoute
  DebugEnvRoute: typeof DebugEnvRoute
  HiringAlfredRoute: typeof HiringAlfredRoute
  MediaRoute: typeof MediaRoute
  ProductThinkingRoute: typeof ProductThinkingRoute
  RecognitionRoute: typeof RecognitionRoute
  StoryRoute: typeof StoryRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesOsmosisRoute: typeof CaseStudiesOsmosisRoute
  CaseStudiesRoomzRoute: typeof CaseStudiesRoomzRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recognition': {
      id: '/recognition'
      path: '/recognition'
      fullPath: '/recognition'
      preLoaderRoute: typeof RecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-thinking': {
      id: '/product-thinking'
      path: '/product-thinking'
      fullPath: '/product-thinking'
      preLoaderRoute: typeof ProductThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring-alfred': {
      id: '/hiring-alfred'
      path: '/hiring-alfred'
      fullPath: '/hiring-alfred'
      preLoaderRoute: typeof HiringAlfredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-env': {
      id: '/debug-env'
      path: '/debug-env'
      fullPath: '/debug-env'
      preLoaderRoute: typeof DebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-strategy': {
      id: '/community-strategy'
      path: '/community-strategy'
      fullPath: '/community-strategy'
      preLoaderRoute: typeof CommunityStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/roomz': {
      id: '/case-studies/roomz'
      path: '/case-studies/roomz'
      fullPath: '/case-studies/roomz'
      preLoaderRoute: typeof CaseStudiesRoomzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/osmosis': {
      id: '/case-studies/osmosis'
      path: '/case-studies/osmosis'
      fullPath: '/case-studies/osmosis'
      preLoaderRoute: typeof CaseStudiesOsmosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityStrategyRoute: CommunityStrategyRoute,
  DebugEnvRoute: DebugEnvRoute,
  HiringAlfredRoute: HiringAlfredRoute,
  MediaRoute: MediaRoute,
  ProductThinkingRoute: ProductThinkingRoute,
  RecognitionRoute: RecognitionRoute,
  StoryRoute: StoryRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesOsmosisRoute: CaseStudiesOsmosisRoute,
  CaseStudiesRoomzRoute: CaseStudiesRoomzRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
